#!/usr/bin/env python

import sys
import os
import inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
grand_parentdir = os.path.dirname(os.path.dirname(currentdir))
sys.path.insert(0, grand_parentdir)
import sconstruct_utils as su
from SCons.Script import Environment, Decider, ADD_BUILDERS, Depends, \
    build_scale_variation_yodas, build_yodas_from_hepmcs, build_merged_yodas

env = Environment(ENV=os.environ, tools=['default', ADD_BUILDERS])
# We use timestamps instead of MD5s since hepmc's are big
Decider('timestamp-match')

base_analysis = 'WHIZARD'
analysiss = [base_analysis]
env['NUMTHREADS'] = '4'
env['ANALYSIS'] = base_analysis
configs = [base_analysis, base_analysis + '-show-MCerrors']
configs = [c + '.plot' for c in configs]
configs = ['WHIZARD.plot']
#  processes = ['jjjj', 'jjjj_ww', 'jjjj_resonances', 'jjjj_resonances_osl1'
processes = ['jjjj', 'jjjj_ww', 'jjjj_resonances'
      ]

plot_together = [{'target': 'plots',
                  #  'lines': ['jjjj', 'jjjj_ww', 'jjjj_resonances', 'jjjj_resonances_osl1'
                  'lines': ['jjjj', 'jjjj_ww', 'jjjj_resonances',
                    ]}
                  ]
descriptions = [r"4j", r"$ W^+ W^- \to 4j$", r"$4j$ (with resonances, OSL=4)",
                r"$4j$ (with resonances, OSL=1)"]
plot_targets = ['plots', 'show-MCerrors']
lo_nlo_lines_and_nlo_band = []
# lo_nlo_lines_and_nlo_band = ['proc_lo.yoda', 'proc_nlo_central.yoda',
#         'envelope.yoda']

make_plot_dir = lambda d : d + '/index.html'
control_plots = map(make_plot_dir, processes)
plot_targets = map(make_plot_dir, plot_targets)
for idx, pd in enumerate(plot_together):
  plot_together[idx]['target'] = make_plot_dir(pd['target'])


def main(control_plots):
  analysis = env.Analysis("RivetAnalysis", analysiss)

  print 'processes: ', processes
  build_yodas_from_hepmcs(env, processes)
  small_yoda_names = su.get_yodas_from_proc_list(processes)
  print 'small_yoda_names: ', small_yoda_names
  n_yodas = len(sum(small_yoda_names, []))
  Depends(small_yoda_names, analysis)
  if n_yodas > 0:
    final_yoda_names = su.get_final_yoda_names(small_yoda_names)
    print 'final_yoda_names: ', final_yoda_names
    merged_yodas = build_merged_yodas(env, small_yoda_names, final_yoda_names)
    scale_variation_yodas = su.find_scale_variation_yodas(merged_yodas)
    final_nlo_yodas = build_scale_variation_yodas(scale_variation_yodas, env)
    if len(final_nlo_yodas) > 0:
      small_yoda_names = small_yoda_names + final_nlo_yodas
      control_plots += map(make_plot_dir, final_nlo_yodas)
      env.BuildEnvelope(target='envelope.yoda', source=final_nlo_yodas)

    print 'Control plots: ', control_plots
    for (small_yodas, control_plot) in zip(small_yoda_names, control_plots):
      # TODO: (bcn 2016-05-26) Use all given configs
      try:
        if len(small_yodas) == 0:
          raise IndexError
        plot = env.Plot(target=control_plot, source=small_yodas, CONFIG=configs[0])
        Depends(plot, configs[0])
      except IndexError:
        print 'Could not build', control_plot, 'from', small_yodas

    if len(lo_nlo_lines_and_nlo_band) > 0:
      env.PlotLOLineWithNLOBand(target=plot_targets[0],
          source=lo_nlo_lines_and_nlo_band, CONFIG=configs[0])

    if len(plot_together) > 0:
      for plot_dict in plot_together:
        env.Plot(target=plot_dict['target'], source=plot_dict['lines'],
            CONFIG=configs[0], DESCRIPTIONS=descriptions)

main(control_plots)
