#!/usr/bin/env python

import sys
import os
import inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
grand_parentdir = os.path.dirname(os.path.dirname(currentdir))
sys.path.insert(0, grand_parentdir)
import sconstruct_utils as su
import shutil

env = Environment(ENV=os.environ, tools=['default', ADD_BUILDERS])

# We use timestamps instead of MD5s since hepmc's are big
Decider('timestamp-match')
base_analysis = 'WHIZARD_H4l2b_NLO'
analysiss = [base_analysis]
env['NUMTHREADS'] = '4'

dirify = lambda d : d + '/index.html'

processes =  ['proc_lo',
             'proc_nlo_low_Born', 'proc_nlo_low_Real', 'proc_nlo_low_Virtual', 'proc_nlo_low_Mismatch',
             'proc_nlo_central_Born', 'proc_nlo_central_Real', 'proc_nlo_central_Virtual', 'proc_nlo_central_Mismatch',
             'proc_nlo_high_Born', 'proc_nlo_high_Real', 'proc_nlo_high_Virtual', 'proc_nlo_high_Mismatch']
# processes = su.filter_existing_processes (processes, 'yoda')


control_plots = map(dirify, processes)
descriptions = [r"\textsc{LO}", r"\textsc{NLO}", r"\textsc{POWHEG}"]

# This is a list of plots corresponding to a list of configs
plots = ['plots', 'show-MCerrors']
plots = map(dirify, plots)
configs = [base_analysis, base_analysis + '-show-MCerrors']
configs = [c + '.plot' for c in configs]

small_yoda_names = su.get_yodas_from_proc_list (processes)
# print 'small_yoda_names: ', small_yoda_names
final_yoda_names = su.get_final_yoda_names (small_yoda_names)
#print 'final_yoda_names: ', final_yoda_names

Analysis = env.Analysis('RivetAnalysis', analysiss)
merged_yodas = []

for small_yoda, yoda in zip (small_yoda_names, final_yoda_names):
  if len (small_yoda) > 1:
    merged_yodas.append (env.MergeYodas(target = yoda, source = small_yoda))
  else:
    shutil.copyfile (str (small_yoda[0]), yoda)
    merged_yodas.append (yoda)

lo_low_yodas = []
lo_central_yodas = []
lo_high_yodas = []
nlo_low_yodas = []
nlo_central_yodas = []
nlo_high_yodas = []
for yoda in merged_yodas:
    print 'yoda name: ', str (yoda)
    if 'nlo_low' in str (yoda):
      nlo_low_yodas.append(yoda)
    elif 'nlo_central' in str (yoda):
      nlo_central_yodas.append(yoda)
    elif 'nlo_high' in str (yoda):
      nlo_high_yodas.append(yoda)
    elif 'lo_low' in str (yoda):
      lo_low_yodas.append(yoda)
    elif 'lo_central' in str (yoda):
      lo_central_yodas.append(yoda)
    elif 'lo_high' in str (yoda):
      lo_high_yodas.append(yoda)

#print 'Merge NLO yodas (?)'
#print 'nlo_low_yodas: ', nlo_low_yodas
#print 'nlo_central_yodas: ', nlo_central_yodas
#print 'nlo_high_yodas: ', nlo_high_yodas
env.MergeYodasNoScale (target = 'proc_nlo_low.yoda', source = nlo_low_yodas)
env.MergeYodasNoScale (target = 'proc_nlo_central.yoda', source = nlo_central_yodas)
env.MergeYodasNoScale (target = 'proc_nlo_high.yoda', source = nlo_high_yodas)
# final_yodas = [merged_yodas[0], merged_yodas[1], merged_yodas[2]]
final_nlo_yodas = ['proc_nlo_central.yoda', 'proc_nlo_low.yoda', 'proc_nlo_high.yoda']
small_yoda_names = small_yoda_names + final_nlo_yodas
control_plots = control_plots + map(dirify, ['proc_nlo_low', 'proc_nlo_central', 'proc_nlo_high'])
# control_plots = control_plots + map(dirify, ['proc_nlo_central'])

env.BuildEnvelope (target = 'envelope.yoda', source = final_nlo_yodas)

#print 'Control plots: ', control_plots
for (small_yodas, control_plot) in zip(small_yoda_names, control_plots):
  plot = env.Plot(target = control_plot, source = small_yodas, CONFIG=configs[0])
  Depends(plot, configs[0])

env.Plot (target = 'proc_nlo/index.html', source = ['proc_nlo_low.yoda', 'proc_nlo_central.yoda', 'proc_nlo_high.yoda'], CONFIG=configs[0])
# env.Plot (target = 'proc_nlo/index.html', source = ['proc_nlo_central.yoda'], CONFIG=configs[0])

env.PlotLOLineWithNLOBand(target = plots[0], source = ['proc_lo.yoda', 'proc_nlo_central.yoda', 'envelope.yoda'],
   CONFIG=configs[0])

# env.Plot (target = plots[0], source = ['proc_lo.yoda', 'proc_nlo_central.yoda'],
#   CONFIG=configs[0])
